name: Go

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      with:
        go-version: 1.17
    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v5.2.0
    - name: Build
      run: |
        mkdir -p output
        GOOS=windows GOARCH=amd64 go build -o output/cf_windows_x64
        GOOS=windows GOARCH=arm64 go build -o output/cf_windows_arm64
        GOOS=linux GOARCH=amd64 go build -o output/cf_linux_x64
        GOOS=linux GOARCH=arm64 go build -o output/cf_linux_arm64
        GOOS=darwin GOARCH=amd64 go build -o output/cf_macos_x64
        GOOS=darwin GOARCH=arm64 go build -o output/cf_macos_arm64
        ls -al output

